[package]
name = "mainnet-runtime"
description = "Official Analog Timechain Mainnet Runtime"
build = "build.rs"
license = "Apache-2.0"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true }

scale-codec = { workspace = true, features = [ "max-encoded-len" ] }
scale-info = { workspace = true, features = [ "serde" ] }
serde_json = { workspace = true, features = ["alloc", "arbitrary_precision"] }

static_assertions = "1.1.0"

primitive-types = { version = "0.13.1", default-features = false, features = ["codec", "scale-info"] }

polkadot-sdk = { workspace = true, features = [
	"frame-election-provider-support",
	"frame-executive",
	"frame-metadata-hash-extension",
	"frame-support",
	"frame-system",
	"frame-system-rpc-runtime-api",

	"pallet-authority-discovery",
	"pallet-authorship",
	"pallet-babe",
	"pallet-bags-list",
	"pallet-balances",
	"pallet-bounties",
	"pallet-child-bounties",
	"pallet-collective",
	"pallet-election-provider-multi-phase",
	"pallet-grandpa",
	"pallet-identity",
	"pallet-im-online",
	"pallet-membership",
	"pallet-multisig",
	"pallet-offences",
	"pallet-preimage",
	"pallet-proxy",
	"pallet-ranked-collective",
	"pallet-referenda",
	"pallet-scheduler",
	"pallet-session",
	"pallet-staking",
	"pallet-staking-reward-curve",
	"pallet-staking-runtime-api",
	"pallet-timestamp",
	"pallet-tips",
	"pallet-transaction-payment",
	"pallet-transaction-payment-rpc-runtime-api",
	"pallet-treasury",
	"pallet-utility",
	"pallet-vesting",
	"pallet-safe-mode",

	"polkadot-runtime-common",

 	"sp-api",
	"sp-block-builder",
	"sp-authority-discovery",
	"sp-consensus-babe",
	"sp-consensus-grandpa",
	"sp-core",
	"sp-genesis-builder",
	"sp-inherents",
	"sp-io",
	"sp-offchain",
	"sp-runtime",
	"sp-session",
	"sp-staking",
	"sp-std",
	"sp-storage",
	"sp-transaction-pool",
	"sp-version",
]}

# Custom local pallets
pallet-dmail.workspace = true
pallet-elections.workspace = true
pallet-governance.workspace = true
pallet-members.workspace = true
pallet-networks.workspace = true
pallet-shards.workspace = true
pallet-tasks.workspace = true
pallet-timegraph.workspace = true

# shared code between runtimes and/or node
runtime-common.workspace = true
time-primitives.workspace = true

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
with-tracing = ["polkadot-sdk/with-tracing"]
std = [
	"log/std",
	"scale-codec/std",
	"scale-info/std",
	"serde_json/std",
	"primitive-types/std",
	"polkadot-sdk/std",

	"pallet-elections/std",
	"pallet-governance/std",
	"pallet-members/std",
	"pallet-networks/std",
	"pallet-dmail/std",
	"pallet-shards/std",
	"pallet-tasks/std",
	"pallet-timegraph/std",

	"runtime-common/std",
	"time-primitives/std",

	"substrate-wasm-builder",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
	"polkadot-sdk/frame-system-benchmarking",
	"polkadot-sdk/pallet-election-provider-support-benchmarking",
	"polkadot-sdk/pallet-offences-benchmarking",
	"polkadot-sdk/pallet-session-benchmarking",
	"polkadot-sdk/pallet-proxy",
	"polkadot-sdk/pallet-multisig",
	"polkadot-sdk/pallet-vesting",
	"polkadot-sdk/pallet-referenda",
	"polkadot-sdk/pallet-preimage",
	"polkadot-sdk/pallet-scheduler",
	"polkadot-sdk/pallet-identity",
	"polkadot-sdk/pallet-collective",
	"polkadot-sdk/pallet-membership",
	"polkadot-sdk/pallet-ranked-collective",
	"polkadot-sdk/pallet-treasury",
	"polkadot-sdk/pallet-bounties",
	"polkadot-sdk/pallet-child-bounties",
	"polkadot-sdk/pallet-tips",
	"polkadot-sdk/pallet-safe-mode",
	"pallet-elections/runtime-benchmarks",
	"pallet-governance/runtime-benchmarks",
	"pallet-members/runtime-benchmarks",
	"pallet-networks/runtime-benchmarks",
	"pallet-dmail/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
	"pallet-tasks/runtime-benchmarks",
	"pallet-timegraph/runtime-benchmarks",
	"runtime-common/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",
	"polkadot-sdk/frame-try-runtime",
	"pallet-elections/try-runtime",
	"pallet-governance/try-runtime",
	"pallet-members/try-runtime",
	"pallet-networks/try-runtime",
	"pallet-dmail/try-runtime",
	"pallet-shards/try-runtime",
	"pallet-tasks/try-runtime",
	"pallet-timegraph/try-runtime",
]
development = [
	"runtime-common/development"
]
