config:
  chronicle_funds: 10.
  timechain_url: 'ws://validator:9944'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "factory/additional_config.json"
    proxy: "contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
networks:
  0:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "http://chain-0-grpc:3000"
    admin_funds: 10.
    gateway_funds: 10.
    chronicle_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000
    # This is the base fee of evm chains. Connector have a method to fetch base fee:
    # https://github.com/Analog-Labs/chain-connectors/blob/master/chains/ethereum/server/src/utils.rs#L296
    # In short it queries the fee history for some past blocks 10/15 and takes median of it.
    # TODO remove from here and fetch from connector when evm backend is functional
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
  1:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "http://chain-1-grpc:3000"
    admin_funds: 10.
    gateway_funds: 10.
    chronicle_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 1715000000000
    shard_size: 1
    shard_threshold: 1
  2:
    backend: "evm"
    blockchain: "anvil"
    network: "dev"
    url: "ws://chain-2-evm:8545"
    admin_funds: 10.
    gateway_funds: 1.
    chronicle_funds: 1.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
  3:
    backend: "evm"
    blockchain: "anvil"
    network: "dev"
    url: "ws://chain-3-evm:8545"
    admin_funds: 10.
    gateway_funds: 1.
    chronicle_funds: 1.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
chronicles:
  - http://timechain-chronicle-0-grpc-1:8080
  - http://timechain-chronicle-1-grpc-1:8080
  - http://timechain-chronicle-2-evm-1:8080
  - http://timechain-chronicle-3-evm-1:8080
