[package]
name = "runtime-common"
authors = [ "Analog Devs <https://github.com/Analog-Labs>" ]
edition = "2021"
homepage = ""
license = "LGPL-3.0"
repository = ""
version = "1.0.0"
[dependencies]
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-v1.8.0", default-features = false }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-v1.8.0", default-features = false }

[features]
default = [ "std" ]
std = [
	"sp-core/std",
	"sp-weights/std",
]
runtime-benchmarks = []
