name: Run end-to-end tests
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  if: false
  test-cargo:
    runs-on: [self-hosted, general]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          args: --all-features --no-run
      - name: Run testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          args: --all-features -p timechain --tests
          cache: false
          annotate: false
